// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Player;

public interface _ServerOperationsNC
{
    String selectSong(Song s);

    void playSong(String token);

    void stopSong(String token);

    void addSong(Song s);

    void removeSong(Song s);

    Song[] searchSong(String artist, String title);

    void uploadFile(String path, byte[] data);
}
