// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Player;

public interface _ServerOperations
{
    String selectSong(Song s, Ice.Current __current);

    void playSong(String token, Ice.Current __current);

    void stopSong(String token, Ice.Current __current);

    void addSong(Song s, Ice.Current __current);

    void removeSong(Song s, Ice.Current __current);

    Song[] searchSong(String artist, String title, Ice.Current __current);
}
