// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Player;

public interface ServerPrx extends Ice.ObjectPrx
{
    public String selectSong(Song s);

    public String selectSong(Song s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_selectSong(Song s);

    public Ice.AsyncResult begin_selectSong(Song s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_selectSong(Song s, Ice.Callback __cb);

    public Ice.AsyncResult begin_selectSong(Song s, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_selectSong(Song s, Callback_Server_selectSong __cb);

    public Ice.AsyncResult begin_selectSong(Song s, java.util.Map<String, String> __ctx, Callback_Server_selectSong __cb);

    public String end_selectSong(Ice.AsyncResult __result);

    public void playSong(String token);

    public void playSong(String token, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_playSong(String token);

    public Ice.AsyncResult begin_playSong(String token, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_playSong(String token, Ice.Callback __cb);

    public Ice.AsyncResult begin_playSong(String token, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_playSong(String token, Callback_Server_playSong __cb);

    public Ice.AsyncResult begin_playSong(String token, java.util.Map<String, String> __ctx, Callback_Server_playSong __cb);

    public void end_playSong(Ice.AsyncResult __result);

    public void stopSong(String token);

    public void stopSong(String token, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopSong(String token);

    public Ice.AsyncResult begin_stopSong(String token, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopSong(String token, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopSong(String token, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopSong(String token, Callback_Server_stopSong __cb);

    public Ice.AsyncResult begin_stopSong(String token, java.util.Map<String, String> __ctx, Callback_Server_stopSong __cb);

    public void end_stopSong(Ice.AsyncResult __result);

    public void addSong(Song s);

    public void addSong(Song s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addSong(Song s);

    public Ice.AsyncResult begin_addSong(Song s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addSong(Song s, Ice.Callback __cb);

    public Ice.AsyncResult begin_addSong(Song s, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_addSong(Song s, Callback_Server_addSong __cb);

    public Ice.AsyncResult begin_addSong(Song s, java.util.Map<String, String> __ctx, Callback_Server_addSong __cb);

    public void end_addSong(Ice.AsyncResult __result);

    public void removeSong(Song s);

    public void removeSong(Song s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeSong(Song s);

    public Ice.AsyncResult begin_removeSong(Song s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeSong(Song s, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeSong(Song s, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeSong(Song s, Callback_Server_removeSong __cb);

    public Ice.AsyncResult begin_removeSong(Song s, java.util.Map<String, String> __ctx, Callback_Server_removeSong __cb);

    public void end_removeSong(Ice.AsyncResult __result);

    public Song[] searchSong(String artist, String title);

    public Song[] searchSong(String artist, String title, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_searchSong(String artist, String title);

    public Ice.AsyncResult begin_searchSong(String artist, String title, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_searchSong(String artist, String title, Ice.Callback __cb);

    public Ice.AsyncResult begin_searchSong(String artist, String title, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_searchSong(String artist, String title, Callback_Server_searchSong __cb);

    public Ice.AsyncResult begin_searchSong(String artist, String title, java.util.Map<String, String> __ctx, Callback_Server_searchSong __cb);

    public Song[] end_searchSong(Ice.AsyncResult __result);
}
