// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `speer_serv.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package speeral;

public enum servStatus implements java.io.Serializable
{
    
    Ready(0),
    
    Running(1),
    
    Stopped(2),
    
    Dead(3);

    public int
    value()
    {
        return __value;
    }

    public static servStatus
    valueOf(int __v)
    {
        switch(__v)
        {
        case 0:
            return Ready;
        case 1:
            return Running;
        case 2:
            return Stopped;
        case 3:
            return Dead;
        }
        return null;
    }

    private
    servStatus(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 3);
    }

    public static servStatus
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(3);
        return __validate(__v);
    }

    private static servStatus
    __validate(int __v)
    {
        final servStatus __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
