// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `servStatus.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package speeral;

public enum servStatus implements java.io.Serializable
{
    
    Ready,
    
    Running,
    
    Stopped,
    
    Dead;

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeByte((byte)ordinal());
    }

    public static servStatus
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readByte(4);
        return values()[__v];
    }
}
