// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `SpeeralError.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package speeral;

public class SpeeralError extends Ice.UserException
{
    public SpeeralError()
    {
    }

    public SpeeralError(Throwable cause)
    {
        super(cause);
    }

    public SpeeralError(String reason)
    {
        this.reason = reason;
    }

    public SpeeralError(String reason, Throwable cause)
    {
        super(cause);
        this.reason = reason;
    }

    public String
    ice_name()
    {
        return "speeral::SpeeralError";
    }

    public String reason;

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString("::speeral::SpeeralError");
        __os.startWriteSlice();
        __os.writeString(reason);
        __os.endWriteSlice();
    }

    public void
    __read(IceInternal.BasicStream __is, boolean __rid)
    {
        if(__rid)
        {
            __is.readString();
        }
        __is.startReadSlice();
        reason = __is.readString();
        __is.endReadSlice();
    }

    public void
    __write(Ice.OutputStream __outS)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "exception speeral::SpeeralError was not generated with stream support";
        throw ex;
    }

    public void
    __read(Ice.InputStream __inS, boolean __rid)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "exception speeral::SpeeralError was not generated with stream support";
        throw ex;
    }
}
